/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as siteRouteRouteImport } from './routes/(site)/route'
import { Route as publicWebinarRouteRouteImport } from './routes/(public)/webinar/route'
import { Route as siteTermsIndexRouteImport } from './routes/(site)/terms/index'
import { Route as sitePrivacyIndexRouteImport } from './routes/(site)/privacy/index'
import { Route as siteContactIndexRouteImport } from './routes/(site)/contact/index'
import { Route as siteAboutIndexRouteImport } from './routes/(site)/about/index'
import { Route as sitehomeIndexRouteImport } from './routes/(site)/(home)/index'
import { Route as publicWebinarIndexRouteImport } from './routes/(public)/webinar/index'
import { Route as protectedSettingIndexRouteImport } from './routes/(protected)/setting/index'
import { Route as protectedProfileIndexRouteImport } from './routes/(protected)/profile/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicWebinarBatchIndexRouteImport } from './routes/(public)/webinar/batch/index'
import { Route as publicauthSignInIndexRouteImport } from './routes/(public)/(auth)/sign-in/index'
import { Route as publicWebinarWatchSlugRouteImport } from './routes/(public)/webinar/watch/$slug'

const siteRouteRoute = siteRouteRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWebinarRouteRoute = publicWebinarRouteRouteImport.update({
  id: '/(public)/webinar',
  path: '/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const siteTermsIndexRoute = siteTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => siteRouteRoute,
} as any)
const sitePrivacyIndexRoute = sitePrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteContactIndexRoute = siteContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteAboutIndexRoute = siteAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => siteRouteRoute,
} as any)
const sitehomeIndexRoute = sitehomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => siteRouteRoute,
} as any)
const publicWebinarIndexRoute = publicWebinarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicWebinarRouteRoute,
} as any)
const protectedSettingIndexRoute = protectedSettingIndexRouteImport.update({
  id: '/(protected)/setting/',
  path: '/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProfileIndexRoute = protectedProfileIndexRouteImport.update({
  id: '/(protected)/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWebinarBatchIndexRoute = publicWebinarBatchIndexRouteImport.update({
  id: '/batch/',
  path: '/batch/',
  getParentRoute: () => publicWebinarRouteRoute,
} as any)
const publicauthSignInIndexRoute = publicauthSignInIndexRouteImport.update({
  id: '/(public)/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWebinarWatchSlugRoute = publicWebinarWatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => publicWebinarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/webinar': typeof publicWebinarRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/': typeof protectedProfileIndexRoute
  '/setting/': typeof protectedSettingIndexRoute
  '/webinar/': typeof publicWebinarIndexRoute
  '/': typeof sitehomeIndexRoute
  '/about/': typeof siteAboutIndexRoute
  '/contact/': typeof siteContactIndexRoute
  '/privacy/': typeof sitePrivacyIndexRoute
  '/terms/': typeof siteTermsIndexRoute
  '/webinar/watch/$slug': typeof publicWebinarWatchSlugRoute
  '/sign-in/': typeof publicauthSignInIndexRoute
  '/webinar/batch/': typeof publicWebinarBatchIndexRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile': typeof protectedProfileIndexRoute
  '/setting': typeof protectedSettingIndexRoute
  '/webinar': typeof publicWebinarIndexRoute
  '/': typeof sitehomeIndexRoute
  '/about': typeof siteAboutIndexRoute
  '/contact': typeof siteContactIndexRoute
  '/privacy': typeof sitePrivacyIndexRoute
  '/terms': typeof siteTermsIndexRoute
  '/webinar/watch/$slug': typeof publicWebinarWatchSlugRoute
  '/sign-in': typeof publicauthSignInIndexRoute
  '/webinar/batch': typeof publicWebinarBatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(site)': typeof siteRouteRouteWithChildren
  '/(public)/webinar': typeof publicWebinarRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/profile/': typeof protectedProfileIndexRoute
  '/(protected)/setting/': typeof protectedSettingIndexRoute
  '/(public)/webinar/': typeof publicWebinarIndexRoute
  '/(site)/(home)/': typeof sitehomeIndexRoute
  '/(site)/about/': typeof siteAboutIndexRoute
  '/(site)/contact/': typeof siteContactIndexRoute
  '/(site)/privacy/': typeof sitePrivacyIndexRoute
  '/(site)/terms/': typeof siteTermsIndexRoute
  '/(public)/webinar/watch/$slug': typeof publicWebinarWatchSlugRoute
  '/(public)/(auth)/sign-in/': typeof publicauthSignInIndexRoute
  '/(public)/webinar/batch/': typeof publicWebinarBatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/webinar'
    | '/api/auth/$'
    | '/profile/'
    | '/setting/'
    | '/webinar/'
    | '/'
    | '/about/'
    | '/contact/'
    | '/privacy/'
    | '/terms/'
    | '/webinar/watch/$slug'
    | '/sign-in/'
    | '/webinar/batch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/auth/$'
    | '/profile'
    | '/setting'
    | '/webinar'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/webinar/watch/$slug'
    | '/sign-in'
    | '/webinar/batch'
  id:
    | '__root__'
    | '/(site)'
    | '/(public)/webinar'
    | '/api/auth/$'
    | '/(protected)/profile/'
    | '/(protected)/setting/'
    | '/(public)/webinar/'
    | '/(site)/(home)/'
    | '/(site)/about/'
    | '/(site)/contact/'
    | '/(site)/privacy/'
    | '/(site)/terms/'
    | '/(public)/webinar/watch/$slug'
    | '/(public)/(auth)/sign-in/'
    | '/(public)/webinar/batch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  siteRouteRoute: typeof siteRouteRouteWithChildren
  publicWebinarRouteRoute: typeof publicWebinarRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  protectedProfileIndexRoute: typeof protectedProfileIndexRoute
  protectedSettingIndexRoute: typeof protectedSettingIndexRoute
  publicauthSignInIndexRoute: typeof publicauthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(site)': {
      id: '/(site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/webinar': {
      id: '/(public)/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof publicWebinarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/terms/': {
      id: '/(site)/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof siteTermsIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/privacy/': {
      id: '/(site)/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof sitePrivacyIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/contact/': {
      id: '/(site)/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof siteContactIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/about/': {
      id: '/(site)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof siteAboutIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/(home)/': {
      id: '/(site)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof sitehomeIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(public)/webinar/': {
      id: '/(public)/webinar/'
      path: '/'
      fullPath: '/webinar/'
      preLoaderRoute: typeof publicWebinarIndexRouteImport
      parentRoute: typeof publicWebinarRouteRoute
    }
    '/(protected)/setting/': {
      id: '/(protected)/setting/'
      path: '/setting'
      fullPath: '/setting/'
      preLoaderRoute: typeof protectedSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/profile/': {
      id: '/(protected)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/webinar/batch/': {
      id: '/(public)/webinar/batch/'
      path: '/batch'
      fullPath: '/webinar/batch/'
      preLoaderRoute: typeof publicWebinarBatchIndexRouteImport
      parentRoute: typeof publicWebinarRouteRoute
    }
    '/(public)/(auth)/sign-in/': {
      id: '/(public)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof publicauthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/webinar/watch/$slug': {
      id: '/(public)/webinar/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/webinar/watch/$slug'
      preLoaderRoute: typeof publicWebinarWatchSlugRouteImport
      parentRoute: typeof publicWebinarRouteRoute
    }
  }
}

interface siteRouteRouteChildren {
  sitehomeIndexRoute: typeof sitehomeIndexRoute
  siteAboutIndexRoute: typeof siteAboutIndexRoute
  siteContactIndexRoute: typeof siteContactIndexRoute
  sitePrivacyIndexRoute: typeof sitePrivacyIndexRoute
  siteTermsIndexRoute: typeof siteTermsIndexRoute
}

const siteRouteRouteChildren: siteRouteRouteChildren = {
  sitehomeIndexRoute: sitehomeIndexRoute,
  siteAboutIndexRoute: siteAboutIndexRoute,
  siteContactIndexRoute: siteContactIndexRoute,
  sitePrivacyIndexRoute: sitePrivacyIndexRoute,
  siteTermsIndexRoute: siteTermsIndexRoute,
}

const siteRouteRouteWithChildren = siteRouteRoute._addFileChildren(
  siteRouteRouteChildren,
)

interface publicWebinarRouteRouteChildren {
  publicWebinarIndexRoute: typeof publicWebinarIndexRoute
  publicWebinarWatchSlugRoute: typeof publicWebinarWatchSlugRoute
  publicWebinarBatchIndexRoute: typeof publicWebinarBatchIndexRoute
}

const publicWebinarRouteRouteChildren: publicWebinarRouteRouteChildren = {
  publicWebinarIndexRoute: publicWebinarIndexRoute,
  publicWebinarWatchSlugRoute: publicWebinarWatchSlugRoute,
  publicWebinarBatchIndexRoute: publicWebinarBatchIndexRoute,
}

const publicWebinarRouteRouteWithChildren =
  publicWebinarRouteRoute._addFileChildren(publicWebinarRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  siteRouteRoute: siteRouteRouteWithChildren,
  publicWebinarRouteRoute: publicWebinarRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  protectedProfileIndexRoute: protectedProfileIndexRoute,
  protectedSettingIndexRoute: protectedSettingIndexRoute,
  publicauthSignInIndexRoute: publicauthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
