---
name: Build and Push Image to Docker Hub
on:
  push:
    tags:
      - '*'

concurrency:
  group: docker-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-docker-release:
    name: Build and Push to Docker Hub ( Release )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
      image-uri: ${{ steps.build-image.outputs.image-uri }}
      commit-sha: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env.production File
        run: echo "${{ vars.ENV_PRODUCTION }}" > .env.production

      - name: Set Image Metadata
        id: meta
        run: |-
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Short SHA: $SHORT_SHA"
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "RELEASE_VERSION=release-${{ github.ref_name }}" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE_NAME }}" >> $GITHUB_ENV
          echo "image-tag=release-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, and Push the Image to Docker Hub
        id: build-image
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          IMAGE_URI="$DOCKER_IMAGE:$IMAGE_TAG"
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag $DOCKER_IMAGE:$IMAGE_TAG \
            --push \
            .
          echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Image pushed: $IMAGE_URI"

      - name: Call Webhook
        uses: joelwmale/webhook-action@2.3.2
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          IMAGE_REGISTRY: Docker Hub
          IMAGE_REPOSITORY: ${{ env.DOCKER_IMAGE }}
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        with:
          url: ${{ secrets.WEBHOOK_URL }}/api/v1/workflow-github?telegram_chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&registry=${{ env.IMAGE_REGISTRY }}
          body: '{"push_data":{"tag":"${{ env.IMAGE_TAG }}"},"repository":{"name":"${{ env.IMAGE_REPOSITORY }}"}}'

  build-push-docker-staging:
    name: Build and Push to Docker Hub ( Staging )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
      image-uri: ${{ steps.build-image.outputs.image-uri }}
      commit-sha: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env.staging File
        run: echo "${{ vars.ENV_STAGING }}" > .env.staging

      - name: Set Image Metadata
        id: meta
        run: |-
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Short SHA: $SHORT_SHA"
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "STAGING_VERSION=staging-${{ github.ref_name }}" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE_NAME }}" >> $GITHUB_ENV
          echo "image-tag=staging-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, and Push the Image to Docker Hub
        id: build-image
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          IMAGE_TAG: ${{ env.STAGING_VERSION }}
        run: |
          IMAGE_URI="$DOCKER_IMAGE:$IMAGE_TAG"
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.dev \
            --tag $DOCKER_IMAGE:$IMAGE_TAG \
            --push \
            .
          echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Image pushed: $IMAGE_URI"

      - name: Call Webhook
        uses: joelwmale/webhook-action@2.3.2
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          IMAGE_REGISTRY: Docker Hub
          IMAGE_REPOSITORY: ${{ env.DOCKER_IMAGE }}
          IMAGE_TAG: ${{ env.STAGING_VERSION }}
        with:
          url: ${{ secrets.WEBHOOK_URL }}/api/v1/workflow-github?telegram_chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&registry=${{ env.IMAGE_REGISTRY }}
          body: '{"push_data":{"tag":"${{ env.IMAGE_TAG }}"},"repository":{"name":"${{ env.IMAGE_REPOSITORY }}"}}'
